/**
 * Greed Island's effect pack: animations any character can play by the GIFX
 * prefix (an Explod with `anim = GIFX1`), loaded by a character that lists
 * it in its .def ([Files] fx = data/gifx/gifx.def). The engine loads a
 * character's packs before compiling its code, which is when the prefix has
 * to be known (vendor/Ikemen-GO src/char.go:3765, 4598; prefixes in
 * src/fightscreen.go:104 and src/compiler.go:6071). Built into
 * IKEMEN_DIR/data/gifx/, outside git like the characters.
 */
import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { writeAir } from "../art/air.ts";
import { writeSff, type SffSprite } from "../art/sff.ts";
import { writeSnd } from "../art/snd.ts";
import { bounds, crop } from "../art/sheet.ts";
import { MARKER } from "../ikemen/derive.ts";
import { hashFiles } from "../templates/build.ts";
import { EXPLOSION_COLORS, EXPLOSION_SIZE, explosionAction, explosionFrames } from "./explosion.ts";

export const FX_PREFIX = "GIFX";
/** The pack's .def, relative to IKEMEN_DIR (what a character's [Files] fx names). */
export const FX_DEF = "data/gifx/gifx.def";
/** The big explosion: `anim = GIFX1`, and its sound `PlaySnd value = GIFX1, 0`. */
export const FX_EXPLOSION = `${FX_PREFIX}1`;

/**
 * The explosion's sound: Counter-Strike 1.6's AWP shot (`weapons/awp1.wav`), from The Sounds Resource
 * (art/SOURCES.md). Not in git: without it the pack is built silent.
 */
export const EXPLOSION_SOUND = {
  file: new URL("../../../../art/sources/cs16/awp1.wav", import.meta.url),
  sha256: "549454453ae2de0df1eaeb3fc74e1bf334fcabd7eb6b03d02121c3dc5a3360c7",
} as const;

/** The explosion's sound if it's been downloaded (and is the right file), else undefined. */
export async function loadExplosionSound(): Promise<Buffer | undefined> {
  if (!existsSync(EXPLOSION_SOUND.file)) return undefined;
  const wav = await readFile(EXPLOSION_SOUND.file);
  const sum = createHash("sha256").update(wav).digest("hex");
  if (sum !== EXPLOSION_SOUND.sha256) throw new Error(`art/sources/cs16/awp1.wav: checksum ${sum} does not match ${EXPLOSION_SOUND.sha256} (art/SOURCES.md)`);
  return wav;
}

function palette(colors: readonly string[]): Uint8Array {
  const out = new Uint8Array(768);
  colors.forEach((c, i) => out.set([parseInt(c.slice(1, 3), 16), parseInt(c.slice(3, 5), 16), parseInt(c.slice(5, 7), 16)], i * 3));
  return out;
}

/** The pack's files, in memory; `sound` is the explosion's (sound 1,0), when there is one. */
export function fxPackFiles(sound?: Buffer): Map<string, Buffer> {
  const { frames, ticks } = explosionFrames();
  const sprites: SffSprite[] = frames.map((img, i) => {
    const b = bounds(img)!;
    return { group: 1, number: i, image: crop(img, b), axisX: EXPLOSION_SIZE.axisX - b.x0, axisY: EXPLOSION_SIZE.axisY - b.y0, palette: 0 };
  });
  const def = [
    "; Greed Island's effect pack (built by pnpm mugen:import). Generated; do not edit.",
    "[Info]",
    `prefix = ${FX_PREFIX}`,
    "fx.scale = 1",
    "localcoord = 320, 240",
    "",
    "[Files]",
    "sff = gifx.sff",
    "air = gifx.air",
    ...(sound ? ["snd = gifx.snd"] : []),
    "",
  ].join("\n");
  return new Map([
    ["gifx.def", Buffer.from(def, "latin1")],
    ["gifx.sff", writeSff(sprites, [{ group: 1, number: 1, colors: palette(EXPLOSION_COLORS) }])],
    ["gifx.air", Buffer.from(writeAir([explosionAction(ticks)], "Greed Island's effect pack. Generated by pnpm mugen:import; do not edit."), "latin1")],
    ...(sound ? [["gifx.snd", writeSnd([{ group: 1, number: 0, wav: sound }])] as [string, Buffer]] : []),
  ]);
}

/** Write the pack into IKEMEN_DIR/data/gifx/ when it changed; never touches a folder without our marker. */
export async function writeFxPack(ikemenDir: string): Promise<"built" | "unchanged"> {
  const files = fxPackFiles(await loadExplosionSound());
  const hash = hashFiles(files);
  const dest = path.join(ikemenDir, path.dirname(FX_DEF));
  const marker = path.join(dest, MARKER);
  if (existsSync(dest)) {
    if (!existsSync(marker)) throw new Error(`${dest} exists and wasn't made by Greed Island; not touching it`);
    if ((JSON.parse(await readFile(marker, "utf8")) as { hash?: string }).hash === hash) return "unchanged";
  }
  const tmp = `${dest}.tmp-${process.pid}`;
  await rm(tmp, { recursive: true, force: true });
  await mkdir(tmp, { recursive: true });
  for (const [name, bytes] of files) await writeFile(path.join(tmp, name), bytes);
  await writeFile(marker.replace(dest, tmp), JSON.stringify({ hash, generatedBy: "pnpm mugen:import" }, null, 2) + "\n");
  await rm(dest, { recursive: true, force: true });
  await rename(tmp, dest);
  return "built";
}
