/**
 * Greed Island's effect pack: animations any character can play by the GIFX
 * prefix (an Explod with `anim = GIFX1`), loaded by a character that lists
 * it in its .def ([Files] fx = data/gifx/gifx.def). The engine loads a
 * character's packs before compiling its code, which is when the prefix has
 * to be known (vendor/Ikemen-GO src/char.go:3765, 4598; prefixes in
 * src/fightscreen.go:104 and src/compiler.go:6071). Built into
 * IKEMEN_DIR/data/gifx/, outside git like the characters.
 */
import { existsSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { writeAir } from "../art/air.ts";
import { writeSff, type SffSprite } from "../art/sff.ts";
import { bounds, crop } from "../art/sheet.ts";
import { MARKER } from "../ikemen/derive.ts";
import { hashFiles } from "../templates/build.ts";
import { EXPLOSION_COLORS, EXPLOSION_SIZE, explosionAction, explosionFrames } from "./explosion.ts";

export const FX_PREFIX = "GIFX";
/** The pack's .def, relative to IKEMEN_DIR (what a character's [Files] fx names). */
export const FX_DEF = "data/gifx/gifx.def";
/** The big explosion: `anim = GIFX1`. */
export const FX_EXPLOSION = `${FX_PREFIX}1`;

function palette(colors: readonly string[]): Uint8Array {
  const out = new Uint8Array(768);
  colors.forEach((c, i) => out.set([parseInt(c.slice(1, 3), 16), parseInt(c.slice(3, 5), 16), parseInt(c.slice(5, 7), 16)], i * 3));
  return out;
}

/** The pack's files, in memory. */
export function fxPackFiles(): Map<string, Buffer> {
  const { frames, ticks } = explosionFrames();
  const sprites: SffSprite[] = frames.map((img, i) => {
    const b = bounds(img)!;
    return { group: 1, number: i, image: crop(img, b), axisX: EXPLOSION_SIZE.axisX - b.x0, axisY: EXPLOSION_SIZE.axisY - b.y0, palette: 0 };
  });
  const def = [
    "; Greed Island's effect pack (built by pnpm mugen:import). Generated; do not edit.",
    "[Info]",
    `prefix = ${FX_PREFIX}`,
    "fx.scale = 1",
    "localcoord = 320, 240",
    "",
    "[Files]",
    "sff = gifx.sff",
    "air = gifx.air",
    "",
  ].join("\n");
  return new Map([
    ["gifx.def", Buffer.from(def, "latin1")],
    ["gifx.sff", writeSff(sprites, [{ group: 1, number: 1, colors: palette(EXPLOSION_COLORS) }])],
    ["gifx.air", Buffer.from(writeAir([explosionAction(ticks)], "Greed Island's effect pack. Generated by pnpm mugen:import; do not edit."), "latin1")],
  ]);
}

/** Write the pack into IKEMEN_DIR/data/gifx/ when it changed; never touches a folder without our marker. */
export async function writeFxPack(ikemenDir: string): Promise<"built" | "unchanged"> {
  const files = fxPackFiles();
  const hash = hashFiles(files);
  const dest = path.join(ikemenDir, path.dirname(FX_DEF));
  const marker = path.join(dest, MARKER);
  if (existsSync(dest)) {
    if (!existsSync(marker)) throw new Error(`${dest} exists and wasn't made by Greed Island; not touching it`);
    if ((JSON.parse(await readFile(marker, "utf8")) as { hash?: string }).hash === hash) return "unchanged";
  }
  const tmp = `${dest}.tmp-${process.pid}`;
  await rm(tmp, { recursive: true, force: true });
  await mkdir(tmp, { recursive: true });
  for (const [name, bytes] of files) await writeFile(path.join(tmp, name), bytes);
  await writeFile(marker.replace(dest, tmp), JSON.stringify({ hash, generatedBy: "pnpm mugen:import" }, null, 2) + "\n");
  await rm(dest, { recursive: true, force: true });
  await rename(tmp, dest);
  return "built";
}
