export { loadRoster, parseRoster, RosterError, ROSTER_PATH, type Roster, type FighterEntry, type StageEntry, type CharacterEntry } from "./roster/schema.ts";
export { scanIkemen, detectLicense, slugify, type ScanResult } from "./roster/scan.ts";
export { syncRoster, RosterSyncError, type SyncReport } from "./roster/sync.ts";
export { missingDefFiles } from "./roster/files.ts";
export { parseIni, iniValue, patchIni } from "./roster/ini.ts";
export { specFromRoster } from "./roster/spec.ts";
export type { EngineMode, EventSource, FightSpec, FighterSpec, RunOptions } from "./types.ts";
export { OutcomeTracker } from "./outcome.ts";
export { createFakeSource, generateScript, seededRandom, type FakeOptions, type FakeScript, type FakeEnding } from "./fake.ts";
export { createIkemenSource, type IkemenSourceOptions } from "./ikemen/runner.ts";
export { buildArgs, statArgs, runConfigIni } from "./ikemen/args.ts";
export { findIkemenBinary, installMod, isModInstalled, MOD_SOURCE } from "./ikemen/install.ts";
export { parseLuaDump, outcomeFromDump, outcomeFromLog, matchDetailFromDump, matchDetailFromLog, type MatchDetail, type RoundDetail } from "./ikemen/log.ts";
export { mirrors, roundRobin, versus, type PlannedFight, type RoundRobinOptions } from "./balance/plan.ts";
export { checkFighter, CheckError, type CheckFighter, type FighterCheckDeps, type FighterCheckInput } from "./balance/check.ts";
export { fighterNumbers, templateFindings, DEFAULT_LIMITS, type FighterNumbers, type MoveNumbers, type TemplateLimits } from "./templates/limits.ts";
export { runSeries, type FightResult, type SeriesOptions } from "./balance/series.ts";
export { summarize, summarizeSides, type SideLine, type SideSummary, wilson, winRate, verdict, DEFAULT_TARGETS, type BalanceSummary, type BalanceTargets, type FighterLine, type Lopsided, type Tally, type Verdict } from "./balance/stats.ts";
export { formatSides, formatSummary } from "./balance/report.ts";
export { loadEngineConfig, type EngineConfig } from "./config.ts";
export { buildVariant, loadVariants, variantDefPath, VariantRecipe, VARIANTS_PATH, type Variant } from "./roster/variants.ts";
export { deriveCharacter, pruneDerived, readConstants, type BaseConstants, type DeriveSpec } from "./ikemen/derive.ts";
export { pruneRuns, runsKeepMs } from "./ikemen/prune-runs.ts";
export { readPng, toRgba, writePng, type PngImage } from "./art/png.ts";
export { mainColors, recolorPalette } from "./art/recolor.ts";
export { readSff, writeSff, type SffPalette, type SffSprite } from "./art/sff.ts";
export { TEMPLATES, templateDefPath } from "./templates/index.ts";
export { hashFiles, writeCharacter, GUIDE_FILE, NUMBERS_FILE, POSE_GUIDE_FILE } from "./templates/build.ts";
export { defFiles, LOOK_PALETTE_FILE, lookFiles, type LookFighter } from "./templates/look.ts";
export { artFromGuide, communityFiles, engineText, guideLayout, guideImage, GuideError, GUIDE_BOX, numbered, POSE_GUIDE_FRAMES, POSE_MAX_FRAMES, portraitArt, sampleArt, type CommunityIdentity, type CommunityImages, type GuideLayout } from "./templates/guide.ts";
