export { loadRoster, parseRoster, RosterError, ROSTER_PATH, type Roster, type FighterEntry, type StageEntry, type CharacterEntry } from "./roster/schema.ts";
export { scanIkemen, detectLicense, slugify, type ScanResult } from "./roster/scan.ts";
export { syncRoster, RosterSyncError, type SyncReport } from "./roster/sync.ts";
export { missingDefFiles } from "./roster/files.ts";
export { parseIni, iniValue, patchIni } from "./roster/ini.ts";
export { specFromRoster } from "./roster/spec.ts";
export type { EngineMode, EventSource, FightSpec, FighterSpec, RunOptions } from "./types.ts";
export { OutcomeTracker } from "./outcome.ts";
export { createFakeSource, generateScript, seededRandom, type FakeOptions, type FakeScript, type FakeEnding } from "./fake.ts";
export { createIkemenSource, type IkemenSourceOptions } from "./ikemen/runner.ts";
export { buildArgs, statArgs, runConfigIni } from "./ikemen/args.ts";
export { findIkemenBinary, installMod, isModInstalled, MOD_SOURCE } from "./ikemen/install.ts";
export { parseLuaDump, outcomeFromDump, outcomeFromLog } from "./ikemen/log.ts";
export { loadEngineConfig, type EngineConfig } from "./config.ts";
export { buildVariant, loadVariants, variantDefPath, VariantRecipe, VARIANTS_PATH, type Variant } from "./roster/variants.ts";
export { deriveCharacter, pruneDerived, readConstants, type BaseConstants, type DeriveSpec } from "./ikemen/derive.ts";
export { pruneRuns, runsKeepMs } from "./ikemen/prune-runs.ts";
