/**
 * A template's character code, generated from its spec: the constants file
 * (patched per fight for upgrades, like any character's), the states (intro,
 * win poses, taunt and every attack) and the commands, with the fighter's AI
 * in [Statedef -1].
 *
 * The AI takes full control of the fighter: AssertSpecial NoAIButtonJam and
 * NoAICheat switch off the engine's random button presses, and AssertInput
 * holds directions for walking, crouching and blocking
 * (vendor/Ikemen-GO src/input.go:2673, src/char.go:5360, src/bytecode.go:11941).
 * Shared states (walking, jumping, guarding, getting hit) come from the
 * engine's common1.cns.
 */
import type { AttackSpec, Command, HitSpec, TemplateSpec } from "./spec.ts";

/** Round for a .cns file. */
function n(x: number): string {
  const r = Math.round(x * 100) / 100;
  return Object.is(r, -0) ? "0" : String(r);
}

function section(title: string, values: Record<string, string | number>): string {
  return [`[${title}]`, ...Object.entries(values).map(([k, v]) => `${k} = ${typeof v === "number" ? n(v) : v}`)].join("\n");
}

/** How much bigger the character's own units are than 320-wide units. */
export function unitScale(spec: TemplateSpec): number {
  return spec.art.localcoord / 320;
}

export function constantsFile(spec: TemplateSpec): string {
  const k = unitScale(spec);
  const c = spec.constants;
  return [
    `; ${spec.name} (${spec.archetype}): constants. Generated by pnpm templates:build; do not edit.`,
    `; Speeds and sizes are in this character's own units (localcoord ${spec.art.localcoord}), ${n(k)}x the 320-wide units in the template spec.`,
    "",
    section("Data", {
      life: c.life, attack: c.attack, defence: c.defence, "fall.defence_up": 50, "liedown.time": 60, airjuggle: 15,
      sparkno: 2, "guard.sparkno": 40, "KO.echo": 0, volume: 0, IntPersistIndex: 60, FloatPersistIndex: 40,
    }),
    "",
    section("Size", {
      xscale: 1, yscale: 1,
      "ground.back": c.width[1] * k, "ground.front": c.width[0] * k, "air.back": 12 * k, "air.front": 12 * k,
      height: c.height * k, "attack.dist": 160 * k, "proj.attack.dist": 90 * k, "proj.doscale": 0,
      "head.pos": `${n(-5 * k)}, ${n(-90 * k)}`, "mid.pos": `${n(-5 * k)}, ${n(-60 * k)}`, shadowoffset: 0, "draw.offset": "0, 0",
    }),
    "",
    section("Velocity", {
      "walk.fwd": c.walkFwd * k, "walk.back": c.walkBack * k,
      "run.fwd": `${n(c.runFwd * k)}, 0`, "run.back": `${n(c.hopBack[0] * k)}, ${n(c.hopBack[1] * k)}`,
      "jump.neu": `0, ${n(c.jumpUp * k)}`, "jump.back": c.jumpBack * k, "jump.fwd": c.jumpFwd * k,
      "runjump.back": `${n(c.jumpBack * k)}, ${n(c.jumpUp * 0.96 * k)}`, "runjump.fwd": `${n((c.jumpFwd + 1.5) * k)}, ${n(c.jumpUp * 0.96 * k)}`,
      "airjump.neu": `0, ${n(c.jumpUp * 0.96 * k)}`, "airjump.back": c.jumpBack * k, "airjump.fwd": c.jumpFwd * k,
      "air.gethit.groundrecover": `${n(-0.15 * k)}, ${n(-3.5 * k)}`,
      "air.gethit.airrecover.mul": ".5, .2", "air.gethit.airrecover.add": `0, ${n(-4.5 * k)}`,
      "air.gethit.airrecover.back": -1 * k, "air.gethit.airrecover.fwd": 0,
      "air.gethit.airrecover.up": -2 * k, "air.gethit.airrecover.down": 1.5 * k,
    }),
    "",
    section("Movement", {
      "airjump.num": 0, "airjump.height": 35 * k, yaccel: c.gravity * k,
      "stand.friction": 0.85, "crouch.friction": 0.82,
      "stand.friction.threshold": 2 * k, "crouch.friction.threshold": 0.05 * k,
      "air.gethit.groundlevel": 25 * k, "air.gethit.groundrecover.ground.threshold": -20 * k,
      "air.gethit.groundrecover.groundlevel": 10 * k, "air.gethit.airrecover.threshold": -1 * k,
      "air.gethit.airrecover.yaccel": 0.35 * k, "air.gethit.trip.groundlevel": 15 * k,
      "down.bounce.offset": `0, ${n(20 * k)}`, "down.bounce.yaccel": 0.4 * k, "down.bounce.groundlevel": 12 * k,
      "down.friction.threshold": 0.05 * k,
    }),
    "",
  ].join("\n");
}

const WEIGHT = { light: { anim: "Light", pause: 8, sound: "F5,0" }, medium: { anim: "Medium", pause: 11, sound: "F5,1" }, heavy: { anim: "Hard", pause: 14, sound: "F5,2" } } as const;

function stateType(a: AttackSpec): "S" | "C" | "A" {
  return a.from === "stand" ? "S" : a.from === "crouch" ? "C" : "A";
}

function hitDef(spec: TemplateSpec, a: AttackSpec, h: HitSpec, i: number): string {
  const k = unitScale(spec);
  const w = WEIGHT[h.weight];
  const knock = h.knockdown || h.trip;
  const launch = h.launch ?? (h.trip ? [1.5, -3] : [4, -5]);
  const guard = h.height === "low" ? "LA" : "MA";
  const ground = h.trip ? "Trip" : h.height === "high" ? "High" : "Low";
  const hitAnim = knock ? (h.trip ? w.anim : "Back") : w.anim;
  const values: Record<string, string | number> = {
    type: "HitDef",
    trigger1: `AnimElem = ${h.frames[0]! + 1}`,
    attr: `${stateType(a)}, ${a.special ? "SA" : "NA"}`,
    damage: `${h.damage}, ${h.chip ?? 0}`,
    animtype: hitAnim,
    guardflag: guard,
    hitflag: a.from === "air" ? "MAF" : "MAFD",
    priority: `${a.special ? 4 : 3}, Hit`,
    pausetime: `${w.pause}, ${w.pause}`,
    sparkxy: `${n(-10 * k)}, ${n((h.height === "low" ? -25 : h.height === "mid" ? -55 : -80) * k)}`,
    hitsound: w.sound,
    guardsound: "F6,0",
    "ground.type": ground,
    "ground.slidetime": Math.round(h.hitStun * 0.6),
    "ground.hittime": h.hitStun,
    "guard.slidetime": Math.round(h.blockStun * 0.6),
    "guard.hittime": h.blockStun,
    "ground.velocity": knock ? `${n(-launch[0] * k)}, ${n(launch[1] * k)}` : n(-h.push * k),
    "guard.velocity": n(-h.push * 0.8 * k),
    "air.velocity": `${n(-Math.max(2.5, h.push * 0.6) * k)}, ${n(-4 * k)}`,
    "airguard.velocity": `${n(-h.push * 0.5 * k)}, ${n(-2.5 * k)}`,
    "air.fall": 1,
  };
  if (knock) {
    values.fall = 1;
    values["fall.recover"] = h.trip ? 0 : 1;
  }
  return [`[State ${a.state}, hit ${i + 1}]`, ...Object.entries(values).map(([key, v]) => `${key} = ${typeof v === "number" ? n(v) : v}`)].join("\n");
}

function attackState(spec: TemplateSpec, a: AttackSpec): string {
  const k = unitScale(spec);
  const t = stateType(a);
  const lines = [
    `; ${a.name} (${a.special ? "special" : "normal"}, ${a.command})`,
    `[Statedef ${a.state}]`,
    `type = ${t}`,
    "movetype = A",
    `physics = ${t === "A" ? "A" : t}`,
    `juggle = ${a.special ? 3 : 2}`,
    `poweradd = ${a.special ? 0 : 20}`,
    "ctrl = 0",
    ...(t === "A" ? [] : ["velset = 0, 0"]),
    `anim = ${a.anim.action}`,
    "sprpriority = 2",
    "",
  ];
  for (const m of a.moves ?? []) {
    lines.push(`[State ${a.state}, move]`, "type = VelSet", `trigger1 = AnimElem = ${m.frame + 1}`, `x = ${n(m.x * k)}`, ...(m.y !== undefined ? [`y = ${n(m.y * k)}`] : []), "");
  }
  a.hits.forEach((h, i) => lines.push(hitDef(spec, a, h, i), ""));
  if (t === "A") {
    // Air attacks land when they reach the ground; the animation holds until then.
    lines.push(`[State ${a.state}, land]`, "type = ChangeState", "trigger1 = Vel Y > 0 && Pos Y >= 0", "value = 52", "");
  } else {
    lines.push(`[State ${a.state}, end]`, "type = ChangeState", "trigger1 = AnimTime = 0", `value = ${t === "C" ? 11 : 0}`, "ctrl = 1", "");
  }
  return lines.join("\n");
}

export function statesFile(spec: TemplateSpec): string {
  const parts = [
    `; ${spec.name} (${spec.archetype}): states. Generated by pnpm templates:build; do not edit.`,
    "",
    "; Every tick: when the computer plays this fighter, only its own AI (in the",
    "; commands file) presses buttons.",
    "[Statedef -2]",
    "",
    "[State -2, AI in control]",
    "type = AssertSpecial",
    "trigger1 = AILevel > 0",
    "flag = NoAIButtonJam",
    "flag2 = NoAICheat",
    "ignorehitpause = 1",
    "",
    "; Intro: anim 190 (the engine's pre-intro state 190 moves here).",
    "[Statedef 191]",
    "type = S",
    "ctrl = 0",
    "anim = 190",
    "velset = 0, 0",
    "",
    "[State 191, playing]",
    "type = AssertSpecial",
    "trigger1 = 1",
    "flag = Intro",
    "",
    "[State 191, done]",
    "type = ChangeState",
    "trigger1 = AnimTime = 0",
    "value = 0",
    "",
    "; Win: one of two poses.",
    "[Statedef 180]",
    "type = S",
    "",
    "[State 180, pick]",
    "type = ChangeState",
    "trigger1 = Time = 0",
    "value = 181 + (Random % 2)",
    "",
  ];
  for (const [state, anim] of [[181, 180], [182, 181]] as const) {
    parts.push(
      `[Statedef ${state}]`, "type = S", "ctrl = 0", `anim = ${anim}`, "velset = 0, 0", "",
      `[State ${state}, pose]`, "type = AssertSpecial", "trigger1 = Time < 90", "flag = RoundNotOver", "",
    );
  }
  parts.push(
    "; Taunt",
    "[Statedef 195]", "type = S", "ctrl = 0", "anim = 195", "velset = 0, 0", "",
    "[State 195, done]", "type = ChangeState", "trigger1 = AnimTime = 0", "value = 0", "ctrl = 1", "",
  );
  for (const a of spec.attacks) parts.push(attackState(spec, a));
  return parts.join("\n");
}

const MOTIONS: Record<string, string> = { QCF: "~D, DF, F", QCB: "~D, DB, B", DP: "~F, D, DF" };

function commandDef(c: Command): string {
  const [motion, button] = c.includes("_") ? c.split("_") as [string, string] : [undefined, c];
  if (c === "FF") return ["[Command]", 'name = "FF"', "command = F, F", "time = 10"].join("\n");
  if (c === "BB") return ["[Command]", 'name = "BB"', "command = B, B", "time = 10"].join("\n");
  if (motion) return ["[Command]", `name = "${c}"`, `command = ${MOTIONS[motion]}, ${button}`, "time = 15"].join("\n");
  return ["[Command]", `name = "${c}"`, `command = ${c}`, "time = 1"].join("\n");
}

function cond(...parts: string[]): string {
  return parts.filter(Boolean).join(" && ");
}

export function commandsFile(spec: TemplateSpec): string {
  const k = unitScale(spec);
  const used = new Set<Command>(["FF", "BB", "x", "y", "a", "b"]);
  for (const a of spec.attacks) used.add(a.command);
  const specials = spec.attacks.filter((a) => a.special);
  const normals = spec.attacks.filter((a) => !a.special);
  const ai = spec.ai;
  const lines: string[] = [
    `; ${spec.name} (${spec.archetype}): commands and AI. Generated by pnpm templates:build; do not edit.`,
    "",
    "[Remap]", "x = x", "y = y", "z = z", "a = a", "b = b", "c = c", "s = s", "",
    "[Defaults]", "command.time = 15", "command.buffer.time = 1", "",
    ...[...used].sort().map((c) => commandDef(c) + "\n"),
    ["[Command]", 'name = "recovery"', "command = x+y", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "taunt"', "command = s", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdfwd"', "command = /$F", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdback"', "command = /$B", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdup"', "command = /$U", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holddown"', "command = /$D", "time = 1"].join("\n"), "",
    "[Statedef -1]",
    "",
  ];
  /** A ChangeState; triggers starting with "all:" are triggerall, the rest trigger1, trigger2... */
  const change = (title: string, value: number | string, triggers: string[]) => {
    const all = triggers.filter((t) => t.startsWith("all:")).map((t) => `triggerall = ${t.slice(4)}`);
    const any = triggers.filter((t) => !t.startsWith("all:")).map((t, i) => `trigger${i + 1} = ${t}`);
    lines.push(`[State -1, ${title}]`, "type = ChangeState", `value = ${value}`, ...all, ...any, "");
  };
  const assert = (title: string, flags: string[], triggers: string[]) => {
    lines.push(`[State -1, ${title}]`, "type = AssertInput", ...flags.map((f, i) => `${i === 0 ? "flag" : `flag${i + 1}`} = ${f}`), ...triggers.map((t, i) => `trigger${i + 1} = ${t}`), "");
  };
  const fromState = (a: AttackSpec) => (a.from === "air" ? "StateType = A" : "StateType != A");

  // ----- A person playing: the usual inputs (AILevel = 0). -----
  lines.push("; ----- Player input -----", "");
  for (const a of specials) {
    change(a.name, a.state, [`all:!AILevel`, `all:command = "${a.command}"`, `all:${fromState(a)}`, "ctrl", "StateNo = [200, 699] && MoveContact"]);
  }
  change("Run", 100, ["all:!AILevel", 'all:command = "FF"', "all:StateType = S", "ctrl"]);
  change("Hop back", 105, ["all:!AILevel", 'all:command = "BB"', "all:StateType = S", "ctrl"]);
  change("Taunt", 195, ["all:!AILevel", 'all:command = "taunt"', "all:StateType = S", "ctrl"]);
  for (const a of normals) {
    const crouch = a.from === "crouch" ? 'command = "holddown"' : a.from === "stand" ? 'command != "holddown"' : "";
    change(a.name, a.state, ["all:!AILevel", `all:command = "${a.command}"`, `all:${fromState(a)}`, ...(crouch ? [`all:${crouch}`] : []), "ctrl"]);
  }

  // ----- The computer playing: this archetype's AI. -----
  const dist = (range: number) => `P2BodyDist X <= ${n(range * k)} && P2BodyDist X >= ${n(-10 * k)}`;
  const inFight = "AILevel && RoundState = 2 && P2Life > 0";
  lines.push(
    "; ----- AI -----",
    "; var(50): 1 if this AI decided to block the attack coming now; var(51): was an attack coming last tick.",
    "",
    "[State -1, AI: decide to block]",
    "type = VarSet",
    `trigger1 = ${inFight} && InGuardDist && !var(51)`,
    `var(50) = Random < ${ai.block}`,
    "",
    "[State -1, AI: attack coming]",
    "type = VarSet",
    "trigger1 = AILevel",
    "var(51) = InGuardDist",
    "",
  );
  assert("AI: block", ["B"], [`${inFight} && InGuardDist && var(50)`]);
  assert("AI: block low", ["D"], [`${inFight} && InGuardDist && var(50) && P2StateType = C`]);
  // Combos: a normal that connected cancels into a special in range.
  for (const a of specials) {
    change(`AI: combo into ${a.name}`, a.state, [`all:${inFight}`, "all:StateNo = [200, 499] && MoveHit", `all:${dist(a.ai.range)}`, `Random < ${Math.min(999, ai.aggression * 3)}`]);
  }
  // Anti-air: the opponent jumping in.
  for (const a of spec.attacks.filter((x) => x.ai.antiAir)) {
    change(`AI: anti-air ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", "all:P2StateType = A && P2MoveType != H", `all:${dist(a.ai.range + 15)}`, `all:P2BodyDist Y < ${n(-20 * k)}`, `Random < ${Math.min(999, ai.aggression * 2 * a.ai.weight)}`]);
  }
  // Attacks in range, specials first, each as likely as its weight.
  for (const a of [...specials, ...normals].filter((x) => x.from !== "air")) {
    change(`AI: ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${dist(a.ai.range)}`, `Random < ${Math.round((ai.aggression * a.ai.weight) / 3)}`]);
  }
  for (const a of normals.filter((x) => x.from === "air")) {
    change(`AI: ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType = A", `all:${dist(a.ai.range + 10)}`, `all:P2BodyDist Y > ${n(-40 * k)}`, `Random < ${Math.round((ai.aggression * a.ai.weight) / 2)}`]);
  }
  // Getting in: run when far, jump in sometimes, walk otherwise; back off a little when crowded.
  change("AI: run in", 100, [`all:${inFight}`, "all:ctrl && StateType = S", `all:P2BodyDist X > ${n(ai.range * 2.2 * k)}`, `Random < ${ai.run}`]);
  lines.push("[State -1, AI: stop running]", "type = ChangeState", "value = 0", `trigger1 = AILevel && StateNo = 100 && P2BodyDist X <= ${n(ai.range * 1.1 * k)}`, "");
  change("AI: jump in", 40, [`all:${inFight}`, "all:ctrl && StateType = S", `all:P2BodyDist X = [${n(ai.range * 1.2 * k)}, ${n(ai.range * 2.5 * k)}]`, `Random < ${ai.jump}`]);
  assert("AI: jump forward", ["F"], ["AILevel && StateNo = 40"]);
  assert("AI: walk in", ["F"], [`${inFight} && ctrl && StateType = S && !InGuardDist && P2BodyDist X > ${n(ai.range * k)} && Random < 900`]);
  assert("AI: back off", ["B"], [`${inFight} && ctrl && StateType = S && !InGuardDist && P2BodyDist X < ${n(ai.range * 0.35 * k)} && Random < 300`]);
  lines.push(
    "[State -1, AI: taunt a fallen opponent]",
    "type = ChangeState",
    "value = 195",
    `trigger1 = ${inFight} && ctrl && StateType = S && P2StateType = L && P2BodyDist X > ${n(90 * k)} && Random < 8`,
    "",
  );
  return lines.join("\n");
}

export function defFile(spec: TemplateSpec, palettes: number): string {
  return [
    `; ${spec.name}: a Greed Island fighter template (${spec.archetype}). Generated by pnpm templates:build; do not edit.`,
    `; ${spec.art.credit}`,
    "; Character code: Greed Island.",
    "",
    "[Info]",
    `name = "${spec.name}"`,
    `displayname = "${spec.name}"`,
    "versiondate = 09,30,2026",
    "mugenversion = 1.1",
    'author = "Greed Island"',
    `pal.defaults = ${Array.from({ length: Math.min(4, palettes) }, (_, i) => i + 1).join(",")}`,
    `localcoord = ${spec.art.localcoord},${Math.round((spec.art.localcoord * 3) / 4)}`,
    "",
    "[Files]",
    "cmd = gi.cmd",
    "cns = gi.cns",
    "st = gi-states.cns",
    "stcommon = common1.cns",
    "sprite = gi.sff",
    "anim = gi.air",
    "",
    "[Palette Keymap]",
    "x = 1", "y = 2", "z = 3", "a = 4", "b = 5", "c = 6",
    "",
  ].join("\n");
}
