/**
 * A template's character code, generated from its spec: the constants file
 * (patched per fight for upgrades, like any character's), the states (intro,
 * win poses, taunt and every attack) and the commands, with the fighter's AI
 * in [Statedef -1].
 *
 * The AI takes full control of the fighter: AssertSpecial NoAIButtonJam and
 * NoAICheat switch off the engine's random button presses, and AssertInput
 * holds directions for walking, crouching and blocking
 * (vendor/Ikemen-GO src/input.go:2673, src/char.go:5360, src/bytecode.go:11941).
 * Shared states (walking, jumping, guarding, getting hit) come from the
 * engine's common1.cns.
 */
import type { AttackSpec, Command, HitSpec, TemplateSpec, ThrowSpec } from "./spec.ts";

/** Round for a .cns file. */
function n(x: number): string {
  const r = Math.round(x * 100) / 100;
  return Object.is(r, -0) ? "0" : String(r);
}

function section(title: string, values: Record<string, string | number>): string {
  return [`[${title}]`, ...Object.entries(values).map(([k, v]) => `${k} = ${typeof v === "number" ? n(v) : v}`)].join("\n");
}

/** How much bigger the character's own units are than 320-wide units. */
export function unitScale(spec: TemplateSpec): number {
  return spec.art.localcoord / 320;
}

export function constantsFile(spec: TemplateSpec): string {
  const k = unitScale(spec);
  const c = spec.constants;
  return [
    `; ${spec.name} (${spec.archetype}): constants. Generated by pnpm templates:build; do not edit.`,
    `; Speeds and sizes are in this character's own units (localcoord ${spec.art.localcoord}), ${n(k)}x the 320-wide units in the template spec.`,
    "",
    section("Data", {
      life: c.life, attack: c.attack, defence: c.defence, "fall.defence_up": 50, "liedown.time": 60, airjuggle: 15,
      sparkno: 2, "guard.sparkno": 40, "KO.echo": 0, volume: 0, IntPersistIndex: 60, FloatPersistIndex: 40,
    }),
    "",
    section("Size", {
      xscale: 1, yscale: 1,
      "ground.back": c.width[1] * k, "ground.front": c.width[0] * k, "air.back": 12 * k, "air.front": 12 * k,
      height: c.height * k, "attack.dist": 160 * k, "proj.attack.dist": 90 * k, "proj.doscale": 0,
      "head.pos": `${n(-5 * k)}, ${n(-90 * k)}`, "mid.pos": `${n(-5 * k)}, ${n(-60 * k)}`, shadowoffset: 0, "draw.offset": "0, 0",
    }),
    "",
    section("Velocity", {
      "walk.fwd": c.walkFwd * k, "walk.back": c.walkBack * k,
      "run.fwd": `${n(c.runFwd * k)}, 0`, "run.back": `${n(c.hopBack[0] * k)}, ${n(c.hopBack[1] * k)}`,
      "jump.neu": `0, ${n(c.jumpUp * k)}`, "jump.back": c.jumpBack * k, "jump.fwd": c.jumpFwd * k,
      "runjump.back": `${n(c.jumpBack * k)}, ${n(c.jumpUp * 0.96 * k)}`, "runjump.fwd": `${n((c.jumpFwd + 1.5) * k)}, ${n(c.jumpUp * 0.96 * k)}`,
      "airjump.neu": `0, ${n(c.jumpUp * 0.96 * k)}`, "airjump.back": c.jumpBack * k, "airjump.fwd": c.jumpFwd * k,
      "air.gethit.groundrecover": `${n(-0.15 * k)}, ${n(-3.5 * k)}`,
      "air.gethit.airrecover.mul": ".5, .2", "air.gethit.airrecover.add": `0, ${n(-4.5 * k)}`,
      "air.gethit.airrecover.back": -1 * k, "air.gethit.airrecover.fwd": 0,
      "air.gethit.airrecover.up": -2 * k, "air.gethit.airrecover.down": 1.5 * k,
    }),
    "",
    section("Movement", {
      "airjump.num": 0, "airjump.height": 35 * k, yaccel: c.gravity * k,
      "stand.friction": 0.85, "crouch.friction": 0.82,
      "stand.friction.threshold": 2 * k, "crouch.friction.threshold": 0.05 * k,
      "air.gethit.groundlevel": 25 * k, "air.gethit.groundrecover.ground.threshold": -20 * k,
      "air.gethit.groundrecover.groundlevel": 10 * k, "air.gethit.airrecover.threshold": -1 * k,
      "air.gethit.airrecover.yaccel": 0.35 * k, "air.gethit.trip.groundlevel": 15 * k,
      "down.bounce.offset": `0, ${n(20 * k)}`, "down.bounce.yaccel": 0.4 * k, "down.bounce.groundlevel": 12 * k,
      "down.friction.threshold": 0.05 * k,
    }),
    "",
  ].join("\n");
}

const WEIGHT = { light: { anim: "Light", pause: 8, sound: "F5,0" }, medium: { anim: "Medium", pause: 11, sound: "F5,1" }, heavy: { anim: "Hard", pause: 14, sound: "F5,2" } } as const;

function stateType(a: AttackSpec): "S" | "C" | "A" {
  return a.from === "stand" ? "S" : a.from === "crouch" ? "C" : "A";
}

function hitDef(spec: TemplateSpec, a: AttackSpec, h: HitSpec, i: number): string {
  const k = unitScale(spec);
  const w = WEIGHT[h.weight];
  const knock = h.knockdown || h.trip;
  const launch = h.launch ?? (h.trip ? [1.5, -3] : [4, -5]);
  const guard = h.height === "low" ? "LA" : h.height === "overhead" ? "HA" : "MA";
  const ground = h.trip ? "Trip" : h.height === "high" || h.height === "overhead" ? "High" : "Low";
  const hitAnim = knock ? (h.trip ? w.anim : "Back") : w.anim;
  const values: Record<string, string | number> = {
    type: "HitDef",
    trigger1: `AnimElem = ${h.frames[0]! + 1}`,
    attr: `${stateType(a)}, ${a.special ? "SA" : "NA"}`,
    damage: `${h.damage}, ${h.chip ?? 0}`,
    animtype: hitAnim,
    guardflag: guard,
    hitflag: a.from === "air" ? "MAF" : "MAFD",
    priority: `${a.special ? 4 : 3}, Hit`,
    pausetime: `${w.pause}, ${w.pause}`,
    sparkxy: `${n(-10 * k)}, ${n((h.height === "low" ? -25 : h.height === "mid" ? -55 : -80) * k)}`,
    hitsound: w.sound,
    guardsound: "F6,0",
    "ground.type": ground,
    "ground.slidetime": Math.round(h.hitStun * 0.6),
    "ground.hittime": h.hitStun,
    "guard.slidetime": Math.round(h.blockStun * 0.6),
    "guard.hittime": h.blockStun,
    "ground.velocity": knock ? `${n(-launch[0] * k)}, ${n(launch[1] * k)}` : n(-h.push * k),
    "guard.velocity": n(-h.push * 0.8 * k),
    "air.velocity": `${n(-Math.max(2.5, h.push * 0.6) * k)}, ${n(-4 * k)}`,
    "airguard.velocity": `${n(-h.push * 0.5 * k)}, ${n(-2.5 * k)}`,
    "air.fall": 1,
  };
  if (knock) {
    values.fall = 1;
    values["fall.recover"] = h.trip ? 0 : 1;
  }
  return [`[State ${a.state}, hit ${i + 1}]`, ...Object.entries(values).map(([key, v]) => `${key} = ${typeof v === "number" ? n(v) : v}`)].join("\n");
}

/** A Projectile controller carrying the move's hit (MUGEN's Projectile takes the HitDef parameters). */
function projectileDef(spec: TemplateSpec, a: AttackSpec): string {
  const k = unitScale(spec);
  const p = a.projectile!;
  const hit = hitDef(spec, a, a.hits[0]!, 0).split("\n").slice(1) // drop the [State] line
    .filter((l) => !/^(type|trigger1|priority|pausetime) =/.test(l))
    .map((l) => (l.startsWith("attr = ") ? `attr = S, ${a.special ? "SP" : "NP"}` : l));
  return [
    `[State ${a.state}, projectile]`,
    "type = Projectile",
    `trigger1 = AnimElem = ${p.frame + 1}`,
    `projID = ${a.state}`,
    `projanim = ${a.state + 50}`,
    `projhitanim = ${a.state + 51}`,
    `projremanim = ${a.state + 52}`,
    `velocity = ${n(p.speed * k)}, 0`,
    `offset = ${n(30 * k)}, ${n(-p.height * k)}`,
    "projpriority = 1",
    "projsprpriority = 3",
    `projedgebound = ${n(40 * k)}`,
    `projstagebound = ${n(40 * k)}`,
    "pausetime = 0, 12",
    ...hit,
  ].join("\n");
}

function attackState(spec: TemplateSpec, a: AttackSpec): string {
  const k = unitScale(spec);
  const t = stateType(a);
  const lines = [
    `; ${a.name} (${a.special ? "special" : "normal"}, ${a.command})`,
    `[Statedef ${a.state}]`,
    `type = ${t}`,
    "movetype = A",
    `physics = ${t === "A" ? "A" : t}`,
    `juggle = ${a.special ? 3 : 2}`,
    `poweradd = ${a.special ? 0 : 20}`,
    "ctrl = 0",
    ...(t === "A" ? [] : ["velset = 0, 0"]),
    `anim = ${a.anim.action}`,
    "sprpriority = 2",
    "",
  ];
  for (const m of a.moves ?? []) {
    lines.push(`[State ${a.state}, move]`, "type = VelSet", `trigger1 = AnimElem = ${m.frame + 1}`, `x = ${n(m.x * k)}`, ...(m.y !== undefined ? [`y = ${n(m.y * k)}`] : []), "");
  }
  if (a.throughProjectiles) {
    // NotHitBy with only the projectile attributes, renewed every tick. The stance part stays
    // empty: NotHitBy blocks a hit when either part matches, so "SCA" would stop every attack
    // (vendor/Ikemen-GO src/char.go:10535-10555, src/compiler.go:760-772).
    lines.push(`[State ${a.state}, through projectiles]`, "type = NotHitBy", "trigger1 = 1", "value = , NP, SP, HP", "time = 1", "");
  }
  if (a.projectile) lines.push(projectileDef(spec, a), "");
  else a.hits.forEach((h, i) => lines.push(hitDef(spec, a, h, i), ""));
  if (t === "A") {
    // Air attacks land when they reach the ground; the animation holds until then.
    lines.push(`[State ${a.state}, land]`, "type = ChangeState", "trigger1 = Vel Y > 0 && Pos Y >= 0", "value = 52", "");
  } else {
    lines.push(`[State ${a.state}, end]`, "type = ChangeState", "trigger1 = AnimTime = 0", `value = ${t === "C" ? 11 : 0}`, "ctrl = 1", "");
  }
  return lines.join("\n");
}

/**
 * A throw's states, in the pattern MUGEN characters use: a HitDef with
 * p1stateno/p2stateno moves both fighters into our states; TargetBind holds
 * the victim frame by frame; TargetLifeAdd and TargetState throw it; the
 * victim falls under gravity until it lands in the engine's state 5100.
 */
function throwStates(spec: TemplateSpec, t: ThrowSpec): string {
  const k = unitScale(spec);
  const S = t.state;
  const lines = [
    `; ${t.name} (${t.special ? "special" : "normal"} throw, ${t.command})`,
    `[Statedef ${S}]`, "type = S", "movetype = A", "physics = S", "juggle = 0", "velset = 0, 0", "ctrl = 0", `anim = ${S}`, "sprpriority = 2", "",
  ];
  for (const m of t.moves ?? []) lines.push(`[State ${S}, move]`, "type = VelSet", `trigger1 = AnimElem = ${m.frame + 1}`, `x = ${n(m.x * k)}`, "");
  lines.push(
    `[State ${S}, grab]`, "type = HitDef", `trigger1 = AnimElem = ${t.catchFrames[0]! + 1}`,
    `attr = S, ${t.special ? "ST" : "NT"}`, "hitflag = M-", `priority = ${t.special ? 2 : 1}, Miss`, "sparkno = -1",
    "p1sprpriority = 1", "p1facing = 1", "p2facing = 1", `p1stateno = ${S + 10}`, `p2stateno = ${S + 20}`, "guard.dist = 0", "fall = 1", "",
    `[State ${S}, missed]`, "type = ChangeState", "trigger1 = AnimTime = 0", "value = 0", "ctrl = 1", "",
    `[Statedef ${S + 10}]`, "type = S", "movetype = A", "physics = N", `anim = ${S + 10}`, "velset = 0, 0", `poweradd = ${t.special ? 0 : 30}`, "",
  );
  const lifted = t.hold.findIndex((h) => h.lifted);
  t.hold.forEach((h, i) => {
    if (i > t.release.frame) return;
    const during = i === t.hold.length - 1 ? `AnimElemTime(${i + 1}) >= 0` : `AnimElemTime(${i + 1}) >= 0 && AnimElemTime(${i + 2}) < 0`;
    lines.push(`[State ${S + 10}, hold ${i + 1}]`, "type = TargetBind", `trigger1 = ${during}`, `pos = ${n(h.victim[0] * k)}, ${n(-h.victim[1] * k)}`, "");
  });
  if (lifted >= 0 && lifted < t.release.frame) lines.push(`[State ${S + 10}, lift]`, "type = TargetState", `trigger1 = AnimElem = ${lifted + 1}`, `value = ${S + 21}`, "");
  lines.push(
    `[State ${S + 10}, damage]`, "type = TargetLifeAdd", `trigger1 = AnimElem = ${t.release.frame + 1}`, `value = ${-t.damage}`, "",
    `[State ${S + 10}, throw]`, "type = TargetState", `trigger1 = AnimElem = ${t.release.frame + 1}`, `value = ${S + 22}`, "",
    `[State ${S + 10}, done]`, "type = ChangeState", "trigger1 = AnimTime = 0", "value = 0", "ctrl = 1", "",
  );
  for (const [state, anim, what] of [[S + 20, S + 20, "held"], [S + 21, S + 21, "lifted"]] as const) {
    lines.push(
      `; ${t.name}: the victim, ${what} (these run as the victim, with its own sprites)`,
      `[Statedef ${state}]`, "type = A", "movetype = H", "physics = N", "velset = 0, 0", "",
      `[State ${state}, anim]`, "type = ChangeAnim2", "trigger1 = Time = 0", `value = ${anim}`, "",
      `[State ${state}, let go]`, "type = SelfState", "trigger1 = !GetHitVar(isbound)", "value = 5050", "",
    );
  }
  lines.push(
    `; ${t.name}: the victim, thrown`,
    `[Statedef ${S + 22}]`, "type = A", "movetype = H", "physics = N", `velset = ${n(-t.release.x * k)}, ${n(-t.release.y * k)}`, "",
    `[State ${S + 22}, anim]`, "type = ChangeAnim2", "trigger1 = Time = 0", `value = ${S + 22}`, "",
    `[State ${S + 22}, gravity]`, "type = VelAdd", "trigger1 = Time > 0", `y = ${n(0.45 * k)}`, "",
    `[State ${S + 22}, land]`, "type = SelfState", "trigger1 = Vel Y > 0 && Pos Y >= 0", "value = 5100", "",
  );
  return lines.join("\n");
}

export function statesFile(spec: TemplateSpec): string {
  const parts = [
    `; ${spec.name} (${spec.archetype}): states. Generated by pnpm templates:build; do not edit.`,
    "",
    "; Every tick: when the computer plays this fighter, only its own AI (in the",
    "; commands file) presses buttons.",
    "[Statedef -2]",
    "",
    "[State -2, AI in control]",
    "type = AssertSpecial",
    "trigger1 = AILevel > 0",
    "flag = NoAIButtonJam",
    "flag2 = NoAICheat",
    "ignorehitpause = 1",
    "",
    "; The engine runs player 1 before player 2 each tick, so player 2 always decides knowing what",
    "; player 1 just did. The two AIs take turns going first instead: player 2 on even ticks, player 1",
    "; on odd ones (RunFirst sets the next tick's order: vendor/Ikemen-GO src/char.go:13322-13374).",
    "[State -2, AI: take turns going first]",
    "type = AssertSpecial",
    "trigger1 = AILevel > 0 && (GameTime % 2) = (TeamSide - 1)",
    "flag = RunFirst",
    "ignorehitpause = 1",
    "",
    "; Intro: anim 190 (the engine's pre-intro state 190 moves here).",
    "[Statedef 191]",
    "type = S",
    "ctrl = 0",
    "anim = 190",
    "velset = 0, 0",
    "",
    "[State 191, playing]",
    "type = AssertSpecial",
    "trigger1 = 1",
    "flag = Intro",
    "",
    "[State 191, done]",
    "type = ChangeState",
    "trigger1 = AnimTime = 0",
    "value = 0",
    "",
    "; Win: one of two poses.",
    "[Statedef 180]",
    "type = S",
    "",
    "[State 180, pick]",
    "type = ChangeState",
    "trigger1 = Time = 0",
    "value = 181 + (Random % 2)",
    "",
  ];
  for (const [state, anim] of [[181, 180], [182, 181]] as const) {
    parts.push(
      `[Statedef ${state}]`, "type = S", "ctrl = 0", `anim = ${anim}`, "velset = 0, 0", "",
      `[State ${state}, pose]`, "type = AssertSpecial", "trigger1 = Time < 90", "flag = RoundNotOver", "",
    );
  }
  parts.push(
    "; Taunt",
    "[Statedef 195]", "type = S", "ctrl = 0", "anim = 195", "velset = 0, 0", "",
    "[State 195, done]", "type = ChangeState", "trigger1 = AnimTime = 0", "value = 0", "ctrl = 1", "",
  );
  for (const a of spec.attacks) parts.push(attackState(spec, a));
  for (const t of spec.throws ?? []) parts.push(throwStates(spec, t));
  return parts.join("\n");
}

const MOTIONS: Record<string, string> = { QCF: "~D, DF, F", QCB: "~D, DB, B", DP: "~F, D, DF" };

function commandDef(c: Command): string {
  const [motion, button] = c.includes("_") ? c.split("_") as [string, string] : [undefined, c];
  if (c === "FF") return ["[Command]", 'name = "FF"', "command = F, F", "time = 10"].join("\n");
  if (c === "BB") return ["[Command]", 'name = "BB"', "command = B, B", "time = 10"].join("\n");
  if (motion) return ["[Command]", `name = "${c}"`, `command = ${MOTIONS[motion]}, ${button}`, "time = 15"].join("\n");
  return ["[Command]", `name = "${c}"`, `command = ${c}`, "time = 1"].join("\n");
}

function cond(...parts: string[]): string {
  return parts.filter(Boolean).join(" && ");
}

/**
 * `reach`: each move's measured reach (templates/reach.ts), used instead of
 * the spec's hand-set `ai.range` when given.
 */
export function commandsFile(spec: TemplateSpec, reach?: ReadonlyMap<number, number>): string {
  const k = unitScale(spec);
  const rangeOf = (m: { state: number; ai: { range: number } }) => reach?.get(m.state) ?? m.ai.range;
  // Where to stand: close enough for all but the shortest standing normal to reach (at the
  // longest one's reach, only that move would ever connect), unless the fighter has a
  // projectile (a zoner wants to stay out).
  const standingReaches = spec.attacks.filter((a) => a.from === "stand" && !a.special && !a.projectile).map(rangeOf).sort((a, b) => a - b);
  const standingReach = standingReaches[Math.min(1, standingReaches.length - 1)] ?? 0;
  const spacing = reach && standingReach > 0 && !spec.attacks.some((a) => a.projectile) ? Math.min(spec.ai.range, standingReach) : spec.ai.range;
  const used = new Set<Command>(["FF", "BB", "x", "y", "a", "b"]);
  for (const a of spec.attacks) used.add(a.command);
  for (const t of spec.throws ?? []) if (t.command !== "throw") used.add(t.command);
  const specials = spec.attacks.filter((a) => a.special);
  const normals = spec.attacks.filter((a) => !a.special);
  const ai = spec.ai;
  const lines: string[] = [
    `; ${spec.name} (${spec.archetype}): commands and AI. Generated by pnpm templates:build; do not edit.`,
    "",
    "[Remap]", "x = x", "y = y", "z = z", "a = a", "b = b", "c = c", "s = s", "",
    "[Defaults]", "command.time = 15", "command.buffer.time = 1", "",
    ...[...used].sort().map((c) => commandDef(c) + "\n"),
    ["[Command]", 'name = "recovery"', "command = x+y", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "taunt"', "command = s", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdfwd"', "command = /$F", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdback"', "command = /$B", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holdup"', "command = /$U", "time = 1"].join("\n"), "",
    ["[Command]", 'name = "holddown"', "command = /$D", "time = 1"].join("\n"), "",
    "[Statedef -1]",
    "",
  ];
  /** A ChangeState; triggers starting with "all:" are triggerall, the rest trigger1, trigger2... */
  const change = (title: string, value: number | string, triggers: string[]) => {
    const all = triggers.filter((t) => t.startsWith("all:")).map((t) => `triggerall = ${t.slice(4)}`);
    const any = triggers.filter((t) => !t.startsWith("all:")).map((t, i) => `trigger${i + 1} = ${t}`);
    lines.push(`[State -1, ${title}]`, "type = ChangeState", `value = ${value}`, ...all, ...any, "");
  };
  const assert = (title: string, flags: string[], triggers: string[]) => {
    lines.push(`[State -1, ${title}]`, "type = AssertInput", ...flags.map((f, i) => `${i === 0 ? "flag" : `flag${i + 1}`} = ${f}`), ...triggers.map((t, i) => `trigger${i + 1} = ${t}`), "");
  };
  const fromState = (a: AttackSpec) => (a.from === "air" ? "StateType = A" : "StateType != A");

  // ----- A person playing: the usual inputs (AILevel = 0). -----
  lines.push("; ----- Player input -----", "");
  const throwable = "P2StateType != A && P2StateType != L && P2MoveType != H";
  for (const t of spec.throws ?? []) {
    const input = t.command === "throw" ? ['all:command = "y"', 'all:command = "holdfwd"', `all:${throwable}`, `all:P2BodyDist X <= ${n(rangeOf(t) * k)}`] : [`all:command = "${t.command}"`];
    change(t.name, t.state, ["all:!AILevel", ...input, "all:StateType != A", "ctrl"]);
  }
  for (const a of specials) {
    change(a.name, a.state, [`all:!AILevel`, `all:command = "${a.command}"`, `all:${fromState(a)}`, "ctrl", "StateNo = [200, 699] && MoveContact"]);
  }
  change("Run", 100, ["all:!AILevel", 'all:command = "FF"', "all:StateType = S", "ctrl"]);
  change("Hop back", 105, ["all:!AILevel", 'all:command = "BB"', "all:StateType = S", "ctrl"]);
  change("Taunt", 195, ["all:!AILevel", 'all:command = "taunt"', "all:StateType = S", "ctrl"]);
  for (const a of normals) {
    const crouch = a.from === "crouch" ? 'command = "holddown"' : a.from === "stand" ? 'command != "holddown"' : "";
    change(a.name, a.state, ["all:!AILevel", `all:command = "${a.command}"`, `all:${fromState(a)}`, ...(crouch ? [`all:${crouch}`] : []), "ctrl"]);
  }

  // ----- The computer playing: this archetype's AI. -----
  const dist = (range: number) => `P2BodyDist X <= ${n(range * k)} && P2BodyDist X >= ${n(-10 * k)}`;
  const inFight = "AILevel && RoundState = 2 && P2Life > 0";
  // An attack on its way (the engine works this out once a tick for both fighters, char.go:13484).
  const threat = "InGuardDist";
  // Guarding keeps control (the engine's guard states don't take it away), so an AI that has
  // decided to block must also hold its own attacks back, or it swings straight out of its guard.
  const notBlocking = `!(${threat} && var(50))`;
  lines.push(
    "; ----- AI -----",
    "; var(50): 1 if this AI decided to block the attack coming now; var(52): was a projectile coming",
    "; last tick; var(53): was an attack coming last tick.",
    "",
    "[State -1, AI: decide to block]",
    "type = VarSet",
    `trigger1 = ${inFight} && ${threat} && !var(53)`,
    `var(50) = Random < ${ai.block}`,
    "",
    "; A projectile is slow and seen from far away: decide again when it's on its way, and block most of them.",
    "[State -1, AI: decide to block a projectile]",
    "type = VarSet",
    `trigger1 = ${inFight} && ${threat} && (EnemyNear, NumProj) > 0 && !var(52)`,
    `var(50) = Random < ${ai.blockProjectile ?? 800}`,
    "",
    "; Reacting: an attack already on its way can still be blocked, so slow moves are blocked more than quick ones.",
    "[State -1, AI: react and block]",
    "type = VarSet",
    `trigger1 = ${inFight} && ${threat} && !var(50) && P2MoveType = A && Random < ${ai.react ?? 35}`,
    "var(50) = 1",
    "",
    "[State -1, AI: projectile coming]",
    "type = VarSet",
    "trigger1 = AILevel",
    `var(52) = ${threat} && (EnemyNear, NumProj) > 0`,
    "",
    "[State -1, AI: attack seen]",
    "type = VarSet",
    "trigger1 = AILevel",
    `var(53) = ${threat}`,
    "",

  );
  // A move that goes through projectiles answers one that's on its way (before deciding to block it).
  for (const a of spec.attacks.filter((x) => x.throughProjectiles)) {
    change(`AI: ${a.name} through a projectile`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${threat} && (EnemyNear, NumProj) > 0`, `all:P2BodyDist X <= ${n((rangeOf(a) + 40) * k)}`, `Random < ${ai.throughProjectiles ?? 12}`]);
  }
  assert("AI: block", ["B"], [`${inFight} && ${threat} && var(50)`]);
  assert("AI: block low", ["D"], [`${inFight} && ${threat} && var(50) && P2StateType = C`]);
  // Combos: a normal that connected cancels into a special in range.
  for (const a of specials) {
    change(`AI: combo into ${a.name}`, a.state, [`all:${inFight}`, "all:StateNo = [200, 499] && MoveHit", `all:${dist(rangeOf(a))}`, `Random < ${Math.min(999, ai.aggression * 3)}`]);
  }
  // Anti-air: the opponent jumping in.
  for (const a of spec.attacks.filter((x) => x.ai.antiAir)) {
    change(`AI: anti-air ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${notBlocking}`, "all:P2StateType = A && P2MoveType != H", `all:${dist(rangeOf(a) + 15)}`, `all:P2BodyDist Y < ${n(-20 * k)}`, `Random < ${Math.min(999, ai.aggression * 2 * a.ai.weight)}`]);
  }
  // Throws when close enough, against someone standing or crouching.
  for (const t of spec.throws ?? []) {
    change(`AI: ${t.name}`, t.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${notBlocking}`, `all:${throwable}`, `all:${dist(rangeOf(t))}`, `Random < ${Math.round((ai.aggression * t.ai.weight) / 3)}`]);
  }
  // Attacks in range, specials first, each as likely as its weight.
  for (const a of spec.attacks.filter((x) => x.projectile)) {
    change(`AI: ${a.name} from afar`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${notBlocking}`, `all:P2BodyDist X > ${n(70 * k)}`, `all:NumProjID(${a.state}) = 0`, `Random < ${Math.round((ai.aggression * a.ai.weight) / 3)}`]);
  }
  for (const a of [...specials, ...normals].filter((x) => x.from !== "air" && !x.projectile)) {
    change(`AI: ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType != A", `all:${notBlocking}`, `all:${dist(rangeOf(a))}`, `Random < ${Math.round((ai.aggression * a.ai.weight) / 3)}`]);
  }
  for (const a of normals.filter((x) => x.from === "air")) {
    change(`AI: ${a.name}`, a.state, [`all:${inFight}`, "all:ctrl && StateType = A", `all:${dist(rangeOf(a) + 10)}`, `all:P2BodyDist Y > ${n(-40 * k)}`, `Random < ${Math.round((ai.aggression * a.ai.weight) / 2)}`]);
  }
  // Getting in: run when far, jump in sometimes, walk otherwise; back off a little when crowded.
  change("AI: run in", 100, [`all:${inFight}`, "all:ctrl && StateType = S", `all:${notBlocking}`, `all:P2BodyDist X > ${n(spacing * 2.2 * k)}`, `Random < ${ai.run}`]);
  lines.push("[State -1, AI: stop running]", "type = ChangeState", "value = 0", `trigger1 = AILevel && StateNo = 100 && P2BodyDist X <= ${n(spacing * 1.1 * k)}`, "");
  change("AI: jump in", 40, [`all:${inFight}`, "all:ctrl && StateType = S", `all:${notBlocking}`, `all:P2BodyDist X = [${n(spacing * 1.2 * k)}, ${n(spacing * 2.5 * k)}]`, `Random < ${ai.jump}`]);
  assert("AI: jump forward", ["F"], ["AILevel && StateNo = 40"]);
  assert("AI: walk in", ["F"], [`${inFight} && ctrl && StateType = S && !InGuardDist && P2BodyDist X > ${n(spacing * k)} && Random < 900`]);
  assert("AI: back off", ["B"], [`${inFight} && ctrl && StateType = S && !InGuardDist && P2BodyDist X < ${n(spacing * 0.5 * k)} && Random < ${ai.retreat ?? 300}`]);
  lines.push(
    "[State -1, AI: taunt a fallen opponent]",
    "type = ChangeState",
    "value = 195",
    `trigger1 = ${inFight} && ctrl && StateType = S && P2StateType = L && P2BodyDist X > ${n(90 * k)} && Random < 8`,
    "",
  );
  return lines.join("\n");
}

export function defFile(spec: TemplateSpec, palettes: number): string {
  return [
    `; ${spec.name}: a Greed Island fighter template (${spec.archetype}). Generated by pnpm templates:build; do not edit.`,
    `; ${spec.art.credit}`,
    "; Character code: Greed Island.",
    "",
    "[Info]",
    `name = "${spec.name}"`,
    `displayname = "${spec.name}"`,
    "versiondate = 09,30,2026",
    "mugenversion = 1.1",
    'author = "Greed Island"',
    `pal.defaults = ${Array.from({ length: Math.min(4, palettes) }, (_, i) => i + 1).join(",")}`,
    `localcoord = ${spec.art.localcoord},${Math.round((spec.art.localcoord * 3) / 4)}`,
    "",
    "[Files]",
    "cmd = gi.cmd",
    "cns = gi.cns",
    "st = gi-states.cns",
    "stcommon = common1.cns",
    "sprite = gi.sff",
    "anim = gi.air",
    "",
    "[Palette Keymap]",
    "x = 1", "y = 2", "z = 3", "a = 4", "b = 5", "c = 6",
    "",
  ].join("\n");
}
