/**
 * An NFT look on a fighter's sprites (docs/PHASE3.md "NFTs as fighters",
 * first kind of look): a small character folder whose .def uses the fighter's
 * own files (`../<its folder>/...`) with one palette file of its own, the
 * colour the character wears recoloured in the NFT's main colours. The engine
 * lets an ACT file named in the .def replace palette 1,1 (`loadPalettes`,
 * src/char.go:4466-4492), so a fight plays the look's .def in colour 1. Only
 * for our generated characters (SFF v2 files we wrote). Pure.
 */
import { toRgba, writePng, type PngImage } from "../art/png.ts";
import { actFile, mainColors, paletteAdjacency, recolorPalette } from "../art/recolor.ts";
import { readSff } from "../art/sff.ts";
import { bounds, crop } from "../art/sheet.ts";
import { PROJECTILE_SLOTS } from "./projectile.ts";

/** The look's palette file, next to its .def. */
export const LOOK_PALETTE_FILE = "look.act";

export interface LookFighter {
  /** Its folder under chars/ (one of ours: gi-...). */
  dir: string;
  /** Its .def, as written by our builders. */
  def: string;
  /** Its sprite file (the .def's `sprite`). */
  sff: Uint8Array;
  /** The colour the character wears (palette 1,n). */
  palette: number;
}

export interface LookFiles {
  files: Map<string, Buffer>;
  /** The NFT's main colours used, as #rrggbb. */
  colors: string[];
}

/** A .def's [Files] entries, keys in lower case. */
export function defFiles(def: string): Map<string, string> {
  const out = new Map<string, string>();
  let inFiles = false;
  for (const raw of def.split(/\r?\n/)) {
    const line = raw.replace(/;.*$/, "").trim();
    if (/^\[.*\]$/.test(line)) inFiles = line.toLowerCase() === "[files]";
    else if (inFiles) {
      const m = /^([A-Za-z0-9_.]+)\s*=\s*(.+)$/.exec(line);
      if (m) out.set(m[1]!.toLowerCase(), m[2]!.trim());
    }
  }
  return out;
}

const hex = (c: number) => `#${c.toString(16).padStart(6, "0")}`;

/**
 * The files of a look character `id` (gi-look-...): its .def (the fighter's,
 * with its own files reached through `../<dir>/` and `pal1` set to the look's
 * palette), that palette, and a picture of the fighter in it (`card.png`).
 * Throws when the fighter isn't one of ours or has no colour `palette`, or the
 * NFT's picture has no colours to use.
 */
export function lookFiles(id: string, fighter: LookFighter, image: PngImage): LookFiles {
  if (!/^gi-[a-z0-9-]+$/.test(id) || !/^gi-[a-z0-9-]+$/.test(fighter.dir)) throw new Error("looks are only for Greed Island's own characters");
  const files = defFiles(fighter.def);
  for (const [k, v] of files) if (!/^[A-Za-z0-9_.-]+$/.test(v) && k !== "stcommon") throw new Error(`the fighter's ${k} file isn't in its own folder`);
  const sff = readSff(fighter.sff);
  const base = sff.palettes.findIndex((p) => p.group === 1 && p.number === 1);
  const worn = sff.palettes.find((p) => p.group === 1 && p.number === fighter.palette);
  if (base < 0 || !worn) throw new Error(`the fighter has no colour ${fighter.palette}`);
  const palette = new Uint8Array(768);
  palette.set(worn.colors.subarray(0, 768));
  const drawn = sff.sprites.filter((s) => s.palette === base).map((s) => s.image);
  const usage = new Array<number>(256).fill(0);
  for (const img of drawn) for (const v of img.pixels) usage[v]!++;
  const targets = mainColors(toRgba(image), image.width, image.height);
  if (targets.length === 0) throw new Error("the NFT's picture has no colours to use (it's all transparent)");
  const look = recolorPalette({ palette, usage, adjacency: paletteAdjacency(drawn), targets, keep: new Set(PROJECTILE_SLOTS) });

  // The fighter's .def with its files one folder over, and the look's palette as colour 1.
  const lines = [`; ${id}: an NFT look on ${fighter.dir} (its files, recoloured by ${LOOK_PALETTE_FILE}). Generated by Greed Island; do not edit.`];
  let section = "";
  for (const l of fighter.def.split(/\r?\n/)) {
    const head = /^\s*\[(.*)\]\s*$/.exec(l);
    if (head) {
      section = head[1]!.trim().toLowerCase();
      lines.push(l);
      if (section === "files") lines.push(`pal1 = ${LOOK_PALETTE_FILE}`);
      if (section === "info") lines.push("pal.defaults = 1");
      continue;
    }
    if (/^\s*pal(\d+|\.defaults)\s*=/i.test(l)) continue;
    const m = /^(\s*)([A-Za-z0-9_.]+)(\s*=\s*)([^;]*?)(\s*(;.*)?)$/.exec(l);
    lines.push(section === "files" && m && m[2]!.toLowerCase() !== "stcommon" ? `${m[1]}${m[2]}${m[3]}../${fighter.dir}/${m[4]}${m[5]}` : l);
  }
  if (!files.size) throw new Error("the fighter's .def has no [Files] section");

  const out = new Map<string, Buffer>([
    [`${id}.def`, Buffer.from(lines.join("\n") + "\n", "latin1")],
    [LOOK_PALETTE_FILE, actFile(look)],
  ]);
  // Its stance in the look's colours, for the website.
  const stand = sff.sprites.find((s) => s.group === 0 && s.number === 0 && s.palette === base);
  const b = stand && bounds(stand.image);
  if (stand && b) {
    const img = crop(stand.image, b);
    const rgba = new Uint8Array(img.width * img.height * 4);
    img.pixels.forEach((v, i) => {
      if (v) rgba.set([look[v * 3]!, look[v * 3 + 1]!, look[v * 3 + 2]!, 255], i * 4);
    });
    out.set("card.png", writePng({ width: img.width, height: img.height, colorType: 6, pixels: rgba }));
  }
  return { files: out, colors: targets.map(hex) };
}
