// `pnpm stages:build`: draw Greed Island's own stages (packages/engine/src/stages) into $IKEMEN_DIR/stages/
// as gi-<name>.def and .sff, and a preview of each in runs/stages/. Never overwrites a stage it didn't make.
import { loadRepoEnv, REPO_ROOT } from "@greed-island/db";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { writePng } from "../art/png.ts";
import { HEIGHT, STAGES, stageFiles, WIDTH } from "../stages/stages.ts";
import { loadRoster } from "../roster/schema.ts";

loadRepoEnv();
const ikemenDir = process.env["IKEMEN_DIR"];
if (!ikemenDir) {
  console.error("IKEMEN_DIR is not set. Add IKEMEN_DIR=/path/to/your/Ikemen_GO to .env");
  process.exit(1);
}
const MARK = "Generated by pnpm stages:build";
const roster = await loadRoster();
const previews = path.join(REPO_ROOT, "runs", "stages");
await mkdir(previews, { recursive: true });
for (const design of STAGES) {
  const defFile = path.join(ikemenDir, "stages", `${design.id}.def`);
  if (existsSync(defFile) && !(await readFile(defFile, "utf8")).includes(MARK)) {
    console.error(`  skipped   ${design.name}: ${defFile} exists and wasn't made by Greed Island`);
    continue;
  }
  const { sff, def } = stageFiles(design);
  await writeFile(path.join(ikemenDir, "stages", `${design.id}.sff`), sff);
  await writeFile(defFile, def);
  // A preview: the layers stacked as the camera sees them at the start of a round.
  const rgba = new Uint8Array(WIDTH * HEIGHT * 4);
  for (const l of design.draw()) {
    const pal = l.canvas.palette();
    const left = Math.floor(l.canvas.width / 2 - WIDTH / 2);
    for (let y = 0; y < l.canvas.height && l.y + y < HEIGHT; y++) {
      for (let x = 0; x < WIDTH; x++) {
        const v = l.canvas.pixels[y * l.canvas.width + ((x + left) % l.canvas.width)]!;
        if (v) rgba.set([pal[v * 3]!, pal[v * 3 + 1]!, pal[v * 3 + 2]!, 255], ((l.y + y) * WIDTH + x) * 4);
      }
    }
  }
  await writeFile(path.join(previews, `${design.id}.png`), writePng({ width: WIDTH, height: HEIGHT, colorType: 6, pixels: rgba }));
  const listed = roster.stages.some((s) => s.def === `stages/${design.id}.def`);
  console.log(`  built     ${design.name.padEnd(13)} stages/${design.id}.def (${Math.round(sff.length / 1024)} KB)${listed ? "" : "  (not in roster.json yet)"}`);
}
console.log(`Previews: ${path.relative(REPO_ROOT, previews)}/`);
