/**
 * Build the IKEMEN GO command line for one fight. Every flag here is
 * confirmed in the v1.0.0 source (docs/ikemen-notes.md §1); nothing else is
 * passed. The result is an argument array, never a shell string.
 */
import type { CharacterStats, Side } from "@greed-island/shared";
import { DEFAULT_STATS } from "@greed-island/shared";
import type { FightSpec } from "../types.ts";

export interface RunPaths {
  /** Absolute paths inside runs/<fightId>/. */
  events: string;
  log: string;
  config: string;
  stats: string;
}

export interface ArgOptions {
  mode: "live" | "sim";
  /** AI level for both sides, 1–8. */
  aiLevel: number;
  /** sim only: `-speedtest` multiplier (UNVERIFIED how high is stable). */
  simSpeed: number;
  /** Extra flags appended as-is, e.g. ["-windowed", "-width", "1280", "-height", "720"]. */
  extraArgs?: readonly string[];
}

export interface StatArgs {
  args: string[];
  /** Stats that differ from neutral but have no verified engine mechanism yet. */
  ignored: (keyof CharacterStats)[];
}

/**
 * Map loadout stats to verified flags only. `baseLife` is the fighter's own
 * [Data] life, needed to turn a percentage into -p<n>.lifeMax.
 */
export function statArgs(player: 1 | 2, stats: CharacterStats, baseLife?: number): StatArgs {
  const args: string[] = [];
  const ignored: (keyof CharacterStats)[] = [];
  if (stats.lifePct !== DEFAULT_STATS.lifePct) {
    if (baseLife === undefined) throw new Error("lifePct changes need the fighter's base life");
    const life = Math.max(1, Math.round((baseLife * stats.lifePct) / 100));
    args.push(`-p${player}.lifeMax`, String(life), `-p${player}.life`, String(life));
  }
  if (stats.startPower !== DEFAULT_STATS.startPower) {
    args.push(`-p${player}.power`, String(stats.startPower));
  }
  if (stats.attackPct !== DEFAULT_STATS.attackPct) ignored.push("attackPct");
  if (stats.defensePct !== DEFAULT_STATS.defensePct) ignored.push("defensePct");
  return { args, ignored };
}

export interface BuiltArgs {
  argv: string[];
  ignoredStats: Record<Side, (keyof CharacterStats)[]>;
}

export function buildArgs(spec: FightSpec, paths: RunPaths, options: ArgOptions, baseLife: Partial<Record<Side, number>> = {}): BuiltArgs {
  if (!Number.isInteger(options.aiLevel) || options.aiLevel < 1 || options.aiLevel > 8) {
    throw new Error(`aiLevel must be 1–8, got ${options.aiLevel}`);
  }
  const s1 = statArgs(1, spec.sides[1].stats, baseLife[1]);
  const s2 = statArgs(2, spec.sides[2].stats, baseLife[2]);
  const argv = [
    "-p1", spec.sides[1].defPath,
    "-p2", spec.sides[2].defPath,
    "-p1.ai", String(options.aiLevel),
    "-p2.ai", String(options.aiLevel),
    "-p1.color", String(spec.sides[1].palette),
    "-p2.color", String(spec.sides[2].palette),
    ...s1.args,
    ...s2.args,
    "-s", spec.stage.defPath,
    "-rounds", String(spec.roundsToWin),
    "-log", paths.log,
    "-config", paths.config,
    "-stats", paths.stats,
    "-salty.events", paths.events,
  ];
  if (options.mode === "sim") argv.push("-nosound", "-speedtest", String(options.simSpeed));
  argv.push(...(options.extraArgs ?? []));
  return { argv, ignoredStats: { 1: s1.ignored, 2: s2.ignored } };
}

/** Per-run config: defaults plus one line that loads the event mod in quick VS. */
export function runConfigIni(fightId: string): string {
  return [
    `; Generated by Greed Island for fight ${fightId}.`,
    "; Quick VS exits before external/mods autoload, so load the event mod here.",
    "; See docs/ikemen-notes.md §2.",
    "[Common]",
    "Lua1 = require('external.mods.salty_events')",
    "",
  ].join("\n");
}
